"""Safe in-place updater for v-bot.

Updates only Git-tracked project files. Runtime configuration such as .env and
ignored JSON stores is never reset, cleaned, or regenerated by this updater.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REQUIREMENTS_FILE = ROOT / "requirements.txt"


def _git(*args: str, capture: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=ROOT,
        capture_output=capture,
        text=True,
        check=False,
    )


def _git_available() -> bool:
    return shutil.which("git") is not None


def _working_tree_clean() -> bool:
    result = _git("status", "--porcelain")
    return result.returncode == 0 and not result.stdout.strip()


def update_code() -> tuple[bool, bool, str]:
    """Fast-forward the local checkout and return (success, changed, message)."""
    if not _git_available():
        return False, False, "Git is not installed or is not available in PATH."
    if not (ROOT / ".git").exists():
        return False, False, "This installation is not a Git checkout."
    if not _working_tree_clean():
        return False, False, (
            "Local code changes are present. Commit or stash them before updating; "
            "the updater will not overwrite local work."
        )

    before = _git("rev-parse", "HEAD")
    if before.returncode != 0:
        return False, False, before.stderr.strip() or "Unable to read the current Git commit."
    old_sha = before.stdout.strip()

    fetch = _git("fetch", "--prune", "origin")
    if fetch.returncode != 0:
        return False, False, fetch.stderr.strip() or "Unable to fetch updates from origin."

    pull = _git("pull", "--ff-only", "origin", "main")
    if pull.returncode != 0:
        return False, False, pull.stderr.strip() or "Unable to fast-forward to the latest code."

    after = _git("rev-parse", "HEAD")
    if after.returncode != 0:
        return False, False, after.stderr.strip() or "Unable to verify the updated Git commit."
    new_sha = after.stdout.strip()
    changed = old_sha != new_sha

    if changed:
        return True, True, f"Code updated: {old_sha[:8]} -> {new_sha[:8]}."
    return True, False, "Code is already up to date."


def requirements_changed(old_sha: str | None, new_sha: str | None) -> bool:
    """Return whether requirements.txt changed between two commits."""
    if not old_sha or not new_sha or old_sha == new_sha:
        return False
    result = _git("diff", "--quiet", old_sha, new_sha, "--", "requirements.txt")
    return result.returncode == 1


def current_commit() -> str | None:
    result = _git("rev-parse", "HEAD")
    return result.stdout.strip() if result.returncode == 0 else None
