const $=id=>document.getElementById(id);
const DEMO=window.location.hostname.endsWith("github.io");
const DEMO_TOKEN="vbot-demo-token";
const DEMO_LOGS=["[DEMO] v-bot started successfully","[DEMO] Connected to Discord gateway","[DEMO] No real Discord action was executed"];

function toast(type,title,text){const c=$("toastContainer");if(!c)return;const el=document.createElement("div");el.className="toast "+type;el.innerHTML='<div class="icon">'+(type==="success"?"✓":"!")+'</div><div><strong></strong><span></span></div>';el.querySelector("strong").textContent=title;el.querySelector("span").textContent=text||"";c.appendChild(el);setTimeout(()=>el.remove(),4200)}
function setMessage(id,type,text){const el=$(id);if(!el)return;el.className="message "+type;el.textContent=text}
async function api(path,options={}){if(DEMO)return demoApi(path,options);const r=await fetch(path,{credentials:"same-origin",...options});if(r.status===401){if(location.pathname!=="/signin")location.href="/signin";throw new Error("Authentication required")}let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||"Request failed");return d}
function demoApi(path,options={}){if(path==="/api/login"){let b={};try{b=JSON.parse(options.body||"{}")}catch{}if(b.token!==DEMO_TOKEN)throw new Error("Invalid demo token. Use: vbot-demo-token");return{ok:true}}if(path==="/api/logout")return{ok:true};if(path==="/api/status")return{version:"demo",platform:"github-pages",bot_running:true,pid:12345,dangerous_commands_enabled:false,action_code_ttl:60,demo:true};if(path==="/api/logs")return{lines:DEMO_LOGS};if(path==="/api/action-code"){let b={};try{b=JSON.parse(options.body||"{}")}catch{}return{action:b.action||"unknown",code:"123456",expires_at:Math.floor(Date.now()/1000)+60,demo:true}}throw new Error("Unknown demo endpoint")}

async function refresh(){try{const s=await api("/api/status"),online=!!s.bot_running;const map={botStatus:online?"Online":"Offline",botStatusDetail:online?"Process is running":"Process stopped",botVersion:s.version||"—",codeTtl:s.action_code_ttl??"—",processValue:s.pid?"PID "+s.pid:"—",platformValue:s.platform||"—",protectedValue:s.dangerous_commands_enabled?"Enabled":"Disabled",instanceProcess:s.pid?"PID "+s.pid:"—",instancePlatform:s.platform||"—",instanceProtected:s.dangerous_commands_enabled?"Enabled":"Disabled",instanceStatus:online?"Online":"Offline"};Object.entries(map).forEach(([id,v])=>{if($(id))$(id).textContent=v});if($("status"))$("status").textContent=JSON.stringify(s,null,2);if($("statusDot"))$("statusDot").classList.toggle("online",online);const l=await api("/api/logs"),lines=l.lines?.join("\n")||"No log entries.";if($("logs"))$("logs").textContent=lines;if($("logsFull"))$("logsFull").textContent=lines;if($("connection")){$("connection").classList.add("online");$("connection").innerHTML="<i></i><span>Connected</span>"}}catch(e){if($("connection")){$("connection").classList.remove("online");$("connection").innerHTML="<i></i><span>Offline</span>"}throw e}}

const path=location.pathname;
if(DEMO&&$("mode"))$("mode").textContent="Web Panel • DEMO";
if(DEMO&&$("demoBanner"))$("demoBanner").hidden=false;
if(DEMO&&$("loginHint")){$("loginHint").textContent="Demo token: vbot-demo-token";$("token").value=DEMO_TOKEN}
if($("viewTokenBtn"))$("viewTokenBtn").onclick=()=>{const input=$("token"),button=$("viewTokenBtn"),visible=input.type==="text";input.type=visible?"password":"text";button.textContent=visible?"View":"Hide";input.focus()};
if($("loginForm"))$("loginForm").addEventListener("submit",async e=>{e.preventDefault();const btn=$("loginBtn");btn.disabled=true;btn.textContent="Connecting…";setMessage("loginError","","");try{await api("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:$("token").value})});location.href="/dashboard"}catch(e){setMessage("loginError","error",e.message);toast("error","Connection failed",e.message)}finally{btn.disabled=false;btn.textContent="Sign in"}});
if($("codeBtn"))$("codeBtn").onclick=async()=>{const btn=$("codeBtn");btn.disabled=true;btn.textContent="Generating…";try{const d=await api("/api/action-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:$("action").value})});$("code").textContent=d.code+"  •  "+d.action;if($("codeBox").querySelector(".result-placeholder"))$("codeBox").querySelector(".result-placeholder").hidden=true;setMessage("codeMessage","success","Code generated successfully. It expires automatically.");toast("success","Security code generated",DEMO?"This is a simulated code.":"The code is ready to use.")}catch(e){setMessage("codeMessage","error",e.message);toast("error","Action failed",e.message)}finally{btn.disabled=false;btn.textContent="Generate action code"}};
if($("logoutBtn"))$("logoutBtn").onclick=async()=>{const btn=$("logoutBtn");btn.disabled=true;try{await api("/api/logout",{method:"POST"});location.href="/signin"}catch(e){toast("error","Logout failed",e.message)}finally{btn.disabled=false}};
(async()=>{if(path==="/signin"){if(DEMO){$("token").value=DEMO_TOKEN}return}if(DEMO){await refresh().catch(()=>{});return}try{await refresh()}catch{}})();
if(path!=="/signin")setInterval(()=>refresh().catch(()=>{}),5000);
