"""Centralized runtime security services and sensitive-action authorization."""

from __future__ import annotations

import hashlib
import hmac
import re
import secrets
import threading
import time
from collections import defaultdict, deque
from dataclasses import dataclass
from pathlib import Path

from safe_json import atomic_write, load_object

import config
import security_log


@dataclass(frozen=True, slots=True)
class AuditEntry:
    timestamp: float
    guild_id: int
    channel_id: int
    user_id: int
    command: str
    success: bool


_ACTION_CODE_FILE = Path(__file__).resolve().parent.parent / "action_codes.json"
_ACTION_CODE_LOCK = threading.RLock()
_CODE_PATTERN = re.compile(r"^\d{6}$")


def _code_hash(code: str) -> str:
    return hashlib.sha256(code.encode("ascii")).hexdigest()


def issue_action_code() -> tuple[str, int]:
    """Create a short-lived one-time code for a sensitive command."""
    code = f"{secrets.randbelow(900_000) + 100_000:06d}"
    expires_at = int(time.time() + config.ACTION_CODE_TTL)
    payload = {"code_hash": _code_hash(code), "expires_at": expires_at}
    with _ACTION_CODE_LOCK:
        atomic_write(_ACTION_CODE_FILE, payload, mode=0o600 if config.IS_POSIX else None)
    return code, expires_at


def _consume_action_code(code: str) -> bool:
    if not _CODE_PATTERN.fullmatch(code):
        return False
    with _ACTION_CODE_LOCK:
        data = load_object(_ACTION_CODE_FILE, {})
        if not isinstance(data, dict):
            return False
        expected = data.get("code_hash")
        expires_at = data.get("expires_at")
        if not isinstance(expected, str) or not isinstance(expires_at, int):
            return False
        if expires_at <= int(time.time()):
            _ACTION_CODE_FILE.unlink(missing_ok=True)
            return False
        valid = hmac.compare_digest(_code_hash(code), expected)
        if valid:
            try:
                _ACTION_CODE_FILE.unlink(missing_ok=True)
            except OSError:
                pass
        return valid


async def require_action_code(ctx, action: str) -> bool:
    """Require a one-time six-digit code generated by the local control panel."""
    await ctx.send(
        "🔐 This action requires a one-time 6-digit security code. "
        "Run `action_code` in the local panel, then send the code here within 60 seconds."
    )
    for _ in range(config.ACTION_CODE_MAX_ATTEMPTS):
        try:
            message = await ctx.bot.wait_for(
                "message",
                timeout=config.ACTION_CODE_INPUT_TIMEOUT,
                check=lambda m: m.author.id == ctx.author.id and m.channel.id == ctx.channel.id,
            )
        except TimeoutError:
            await ctx.send("⏰ Security code entry timed out.")
            return False
        code = message.content.strip()
        try:
            await message.delete()
        except Exception:
            pass
        if _consume_action_code(code):
            security_log.log_security_event(
                f"Sensitive action authorized: {action}",
                actor=f"{ctx.author} ({ctx.author.id})",
            )
            return True
        await ctx.send("❌ Invalid or expired security code. Please generate a new code in the local panel.")
        return False
    return False


class SecurityService:
    def __init__(self) -> None:
        self.audit: deque[AuditEntry] = deque(maxlen=config.AUDIT_LOG_RETENTION)
        self._actions: dict[tuple[int, int], deque[float]] = defaultdict(deque)
        self._alert_cooldowns: dict[tuple[int, int], float] = {}

    def record_command(self, *, guild_id: int, channel_id: int, user_id: int, command: str, success: bool) -> bool:
        now = time.monotonic()
        self.audit.append(AuditEntry(now, guild_id, channel_id, user_id, command, success))
        if not success or guild_id <= 0:
            return False
        key = (guild_id, user_id)
        actions = self._actions[key]
        cutoff = now - config.SUSPICIOUS_ACTION_WINDOW
        while actions and actions[0] <= cutoff:
            actions.popleft()
        actions.append(now)
        if len(actions) < config.SUSPICIOUS_ACTION_THRESHOLD:
            return False
        cooldown_until = self._alert_cooldowns.get(key, 0.0)
        if now < cooldown_until:
            return False
        self._alert_cooldowns[key] = now + config.SECURITY_ALERT_COOLDOWN
        security_log.log_security_event(
            f"Suspicious command burst: guild={guild_id} user={user_id} "
            f"{len(actions)} successful commands in {config.SUSPICIOUS_ACTION_WINDOW:.0f}s",
            actor=str(user_id),
        )
        return True

    def prune(self) -> None:
        cutoff = time.monotonic() - config.SUSPICIOUS_ACTION_WINDOW
        for key, actions in list(self._actions.items()):
            while actions and actions[0] <= cutoff:
                actions.popleft()
            if not actions and self._alert_cooldowns.get(key, 0.0) <= time.monotonic():
                self._actions.pop(key, None)
                self._alert_cooldowns.pop(key, None)


security = SecurityService()
