"""Sensitive-action authorization and security helpers."""

from __future__ import annotations

import hashlib
import hmac
import re
import secrets
import threading
import time
from pathlib import Path

import discord

from safe_json import JsonStoreError, atomic_write, load_object

import config
import security_log


_ACTION_CODE_FILE = Path(__file__).resolve().parent.parent / "action_codes.json"
_ACTION_CODE_LOCK = threading.RLock()
_CODE_PATTERN = re.compile(r"^\d{6}$")


def _code_hash(code: str) -> str:
    return hashlib.sha256(code.encode("ascii")).hexdigest()


def issue_action_code() -> tuple[str, int]:
    """Create a short-lived one-time code for a sensitive command."""
    code = f"{secrets.randbelow(900_000) + 100_000:06d}"
    expires_at = int(time.time() + config.ACTION_CODE_TTL)
    payload = {"code_hash": _code_hash(code), "expires_at": expires_at}
    with _ACTION_CODE_LOCK:
        atomic_write(_ACTION_CODE_FILE, payload, mode=0o600 if config.IS_POSIX else None)
    return code, expires_at


def _consume_action_code(code: str) -> bool:
    if not _CODE_PATTERN.fullmatch(code):
        return False
    with _ACTION_CODE_LOCK:
        try:
            data = load_object(_ACTION_CODE_FILE, {})
        except JsonStoreError:
            return False
        if not isinstance(data, dict):
            return False
        expected = data.get("code_hash")
        expires_at = data.get("expires_at")
        if not isinstance(expected, str) or not isinstance(expires_at, int):
            return False
        if expires_at <= int(time.time()):
            try:
                _ACTION_CODE_FILE.unlink(missing_ok=True)
            except OSError:
                pass
            return False
        valid = hmac.compare_digest(_code_hash(code), expected)
        if valid:
            try:
                _ACTION_CODE_FILE.unlink(missing_ok=True)
            except OSError:
                pass
        return valid


async def require_action_code(ctx, action: str) -> bool:
    """Require a one-time six-digit code generated by the local control panel."""
    await ctx.send(
        "🔐 This action requires a one-time 6-digit security code. "
        "Run `action_code` in the local panel, then send the code here within 60 seconds."
    )
    attempts = 0
    deadline = time.monotonic() + config.ACTION_CODE_INPUT_TIMEOUT
    while attempts < config.ACTION_CODE_MAX_ATTEMPTS:
        attempts += 1
        remaining = max(0.1, deadline - time.monotonic())
        try:
            message = await ctx.bot.wait_for(
                "message",
                timeout=remaining,
                check=lambda m: m.author.id == ctx.author.id and m.channel.id == ctx.channel.id,
            )
        except TimeoutError:
            await ctx.send("⏰ Security code entry timed out.")
            return False
        code = message.content.strip()
        try:
            await message.delete()
        except discord.HTTPException:
            pass
        if _consume_action_code(code):
            security_log.log_security_event(
                f"Sensitive action authorized: {action}",
                actor=f"{ctx.author} ({ctx.author.id})",
            )
            return True
        if attempts < config.ACTION_CODE_MAX_ATTEMPTS:
            await ctx.send(f"❌ Invalid security code. Attempt {attempts}/{config.ACTION_CODE_MAX_ATTEMPTS}.")
    await ctx.send("❌ Too many invalid security code attempts. Generate a new code in the local panel.")
    return False
